Task 0

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,8 @@
 #!/bin/bash
-python python_script.py 
+PYFILE="$PYFILE"
+ if [! -f "$PYFILE"];
+then echo "Error: $PYFILE does not exist"
+       exit 1
+fi
+
+python "$PYFILE"
